### ISSUE TITLE
Speedtest result box text and icons not styled

### ISSUE THREAD

**Issue by Seanharrs** [hyperfekt/google-dark#4]
- [X] My version of the userstyle is up to date  
- [X] My version of Stylus is up to date  
- [X] I have added what browser I use and its version.
- [X] I have searched the existing issues (both open *and closed*) to see if my problem is already reported.
- [X] I have given a detailed description of the problem and the steps to reach it.  
- [X] I have added an example URL where the problem occurs.  
- [X] If I have customized any of the options, I have pinned down with which of them it occurs and provided the changed values here.
- [ ] I have saved the page the problem occurs on and attached it here (usually available in the browser context menu).
- [X] I have made a screenshot that demonstrates the problem and attached it here.

Userstyle: Google Dark Search
Stylus version: 1.4.3
Userstyle version: 0.4.5
Browser version: Firefox Developer Edition 61.0b4 (64-bit)

Steps to reach the problem:
1. Navigate to google.com
2. Search for "speedtest"

Expected Behavior: The text and icons in the speed test box should be styled.
Observed Behavior: The text and icons in the speed test box will be unstyled.
URL: https://www.google.com/search?q=speedtest&ie=utf-8&oe=utf-8&client=firefox-b-ab
Customized values that cause the problem: N/A

![speedtest](https://user-images.githubusercontent.com/13175844/40002147-2f3d29f0-57d3-11e8-85ad-a0696bd62e68.JPG)

Do you accept Pull Requests at all? I'd be happy to resolve simple problems like this myself with a PR in future.

**Comment by hyperfekt** [comment]
Generally I'm not opposed to PRs, but the problem is that the quality assurance is practically as much work as doing it myself directly, and the conventions of how different elements are styled is as of yet undocumented.
Some things are indeed simple fixes, and others turn out to have complex interactions with the styling of other elements. This one for example was one of the rather simple ones and still required adding an exception to a completely different rule and one rule for the about link that isn't always applied and therefore noticed - you can see why I'd want to double-check every line of a PR.
